### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Nakaner** [osmfoundation/donation-drive#10]
This repository lacks a license. I would like to know under which condidtions WeeklyOSM could reuse `img/twitter-card.svg` (except the propietary fonts which we will replace by free alternatives).

**Comment by Firefishy** [comment]
My backend code I don't really care as long as something permissive. @mikelmaron @mvexel @zerebubuth ?

**Comment by Nakaner** [comment]
Any news? Due to the unclear status of the license, we removed the image temporarily from the [already published issue](http://blog.openstreetmap.de/blog/2016/10/wochennotiz-nr-324/) of Wochennotiz. All other versions of WeeklyOSM have been finished, too, but are kept back.

Hint: I think that you do not have the necessary rights to distribute Futura font under an open license. Use Open Sans (the image uses it already), instead.

**Comment by Zverik** [comment]
You can use [this svg](https://www.dropbox.com/s/76e4r0ziffnd45f/osm-donate-eng.svg?dl=1): it's made with open fonts ([PT Sans](http://www.paratype.com/public/)) and uses only logo and text which are CC-BY-SA I guess.

**Comment by YunjieLi** [comment]
Thanks for pointing this out @Nakaner @Zverik !
I made some minor changes to the graphics and now only PT Sans is used in twitter-card.svg/png and osm_banner.svg/png/jpg.

I also noticed that the current donation banner on openstreetmap.org looks very blurry. I added an png and an svg to the repo too if we want to point to a different format instead.

cc/ @mikelmaron

**Comment by mikelmaron** [comment]
closing, we confirmed the license. if there's some other step we need to take, please be explicit.
