### ISSUE TITLE
Paypal Donation Flow vs Purchase flow

### ISSUE THREAD

**Issue by Firefishy** [osmfoundation/donation-drive#11]
Currently the code directs the donation through the purchase flow instead of using the Paypal donate flow. https://github.com/osmfoundation/donation-drive/blob/master/process/paypal-submit.php#L41

If the @mikelmaron @mvexel @woodpeck confirm https://www.paypal.com/gb/givingfund/user-agreement#eligibility I can switch the payment flow to donate.

Saving described here: https://www.paypal.com/uk/charities/

**Comment by Firefishy** [comment]
I am conflating 2 different issues here. 1: donate.osm.org should use paypal donation flow, 2: OSMF should apply for paypal charity discount if applicable to OSMF.

Going to close this issue for clarity.

**Comment by mikelmaron** [comment]
for number 2, please flag us again when you open. I'm not sure we're eligible (asks for UK charity status, which I don't believe we have)
