### ISSUE TITLE
New background image

### ISSUE THREAD

**Issue by pnorman** [osmfoundation/donation-drive#2]
The old one worked well for the hardware drive, but something less connected with hardware would be good

![image](https://cloud.githubusercontent.com/assets/1190866/18598313/fdc46fb8-7c06-11e6-9797-d6dd187693c1.png)

**Comment by mikelmaron** [comment]
we have deployed a new bg, visible on https://osmfoundation.github.io/donation-drive/

it's abstract triangles. there is also an OSM logo bg we could try out

**Comment by YunjieLi** [comment]
The visuals are here

Promo card
![osm_banner](https://cloud.githubusercontent.com/assets/12749701/18725002/70493e98-7ff3-11e6-9005-6f522650ab0f.jpg)

Slide (I can make a widescreen one too if needed)
![osm_slide](https://cloud.githubusercontent.com/assets/12749701/18725008/75afc49c-7ff3-11e6-8df1-619d88d4302b.jpg)

Per chat with @mikelmaron I also tested a bit with the website background. The images are all in the repo.

./img/bg_6.svg
![osm_bg1](https://cloud.githubusercontent.com/assets/12749701/18725096/be1d6158-7ff3-11e6-883c-33b931f8f6f4.png)

./img/bg_2.svg
![osm_bg2](https://cloud.githubusercontent.com/assets/12749701/18725105/c7330bd0-7ff3-11e6-9549-be7f7a8bb636.png)

**Comment by Firefishy** [comment]
Remember also the https://donate.openstreetmap.org/img/twitter-card.png file which is used by facebook embedded and likely others.

**Comment by Firefishy** [comment]
NOTE! Site is live and will AUTOMATICALLY update on merges to master (on this repo) within 30mins. Please commit safe. ;-)

**Comment by mikelmaron** [comment]
@Firefishy I quickly pointed twitter card links to the banner image. Looking ok?

**Comment by YunjieLi** [comment]
I replaced the old twitter-card.png with a new one of the same size. I also pointed the links in index.html back to the https://donate.openstreetmap.org/img/twitter-card.png.  Hopefully that would work. 

cc/ @mikelmaron @Firefishy

**Comment by harry-wood** [comment]
I see all these twitter related meta tags for these card images etc (looking great!), but I just posted it to facebook expecting it to automatically put an image in there, but... https://www.facebook.com/OpenStreetMap/  it was a bit disappointing. Guess it needs _more_ meta tags (linkedin will be the next one)

**Comment by YunjieLi** [comment]
twitter-card.svg added to /img folder.
I also darken the green strip in the middle just a tad.

cc/ @mikelmaron

**Comment by Firefishy** [comment]
I think this has been fixed. If still and issue then re-open.
