### ISSUE TITLE
euros by default?

### ISSUE THREAD

**Issue by mikelmaron** [osmfoundation/donation-drive#5]

**Comment by Zverik** [comment]
Our bank account is still in pounds, so we will have to convert currency to display the amount, hence it will change every day in both directions.

**Comment by pnorman** [comment]
We're a UK organization, I'm fine with it being in pounds.

**Comment by pnorman** [comment]
Also, I'm not sure what would be needed on the donation processing backend to change to Euros.

**Comment by mvexel** [comment]
EUR will be better understood globally, I talked to @Firefishy about changes to the back end. I made the changes to the site itself already.

**Comment by Firefishy** [comment]
EUR by default. Due to time constraint am using fixed EUR/GBP conversion. 1GBP = 1.17987EUR. This ratio is from 2013 due to another bug, but should be good enough for now.
