### ISSUE TITLE
We lost the bitcoin wallet number

### ISSUE THREAD

**Issue by Zverik** [osmfoundation/donation-drive#7]
Hi, the CWG just got a mail regarding bitcoin donations. Do we accept these?

**Comment by Firefishy** [comment]
We still list the Bitcoin address here: https://wiki.openstreetmap.org/wiki/Donations#Bitcoin_Donations

But, I am the person responsible for converting BTC to £€$ for buying servers etc and it is becoming increasingly more difficult to convert.

**Comment by Zverik** [comment]
There is a link to that wiki page on the website, so I'm closing the issue. Thanks, Grant.
