### ISSUE TITLE
currency dropdown could change the targetizer display currency

### ISSUE THREAD

**Issue by harry-wood** [osmfoundation/donation-drive#9]
The targetizer display currency is just in euros at the moment right? I guess when you change currency in the little currency dropdown below, it could change the currency of the target display.

Maybe some display width issues in some currencies to figure out.  e.g. 70,000 euros is 1750740894 Vietnamese Dong :-)

**Comment by Zverik** [comment]
There is no target ATM, but when it's added, we'll consider this. Thanks.
